### ISSUE TITLE
如何使用这个库加解密普通字符串？

### ISSUE THREAD

**Issue by mingliao** [windard/sm4#1]
您好，非常感谢您开发了这个库。我是一个新手，现在有一个项目需要前端使用sm4 加密，刚好看到你的这个库。有个问题请教一下：
我看您的例子里面输入的*message*和*key*是十六进制的数组，我们如何传入普通的字符串和key，来加解密。例如```var message=“我爱编程，我爱前端”;var key=“hello_world”``` 。如何得到加密后的文本，以及如何解密。
谢谢了。

**Comment by windard** [comment]
在 `JavaScript/demo` 下提供了一份使用示例，你可以看一下，采用 cbc 模式加密。

**Comment by mingliao** [comment]
@windard 非常感谢。哈哈。
